### ISSUE TITLE
don't unfold all when choosewin

### ISSUE THREAD

**Issue by timfeirg** [t9md/vim-choosewin#11]
this is the current behavior, when use `ChooseWin`, code in all panes is unfolded:

[![asciicast](https://asciinema.org/a/ex9i4cfbeki8yrwaozbxgaop0.png)](https://asciinema.org/a/ex9i4cfbeki8yrwaozbxgaop0)

this can sometimes be distracting, hope there's an option to keep all folding while showing the pane numbers.

**Comment by t9md** [comment]
Are you using overlay screen caption?
Unfolding is necessary for overlaying screen caption.
Because Vim doesn't natively support overlaying font, choosewin temporarily REWRITE buffer and highlight column to form screen caption.
Because of this, unfolding is necessary.
If you dont like undolding, only I can say is disable overlay feature.

Thanks

**Comment by timfeirg** [comment]
thanks! I'll disable overlay, closing this issue
