### ISSUE TITLE
When choosewin is enabled by -, line wrapping is turned off

### ISSUE THREAD

**Issue by ronakg** [t9md/vim-choosewin#19]
I keep line wrapping on. When I press -, line wrapping turns off in all the windows. It's very annoying and distracting.

**Comment by ronakg** [comment]
This happens only when overlay is enabled.

**Comment by t9md** [comment]
Whats the problem? The overlay feature disable line wrap temporarily, then restore line wrap after you chose window.
This is how I expected to work.

Since Vim  don't have native overlay feature, choosewin accomplish overlay by using fill the column with specific color to form label, so I have to disable line wrap to render label correctly.

**Comment by ronakg** [comment]
Oh I see. I now understand how the overlay is implemented. Probably it'll be really difficult to implement it without turning the line wrap off.
